#!/usr/bin/env bash

# Prepare fail to find key
defaultPath=false;

# Look for private key.
[ -f ~/.ssh/id_rsa ] && defaultPath=true ; \

# Inform key not found.
[ "$defaultPath" = "false" ] && echo "E: key not found in default dir." ; \

# Stop the execution.
[ "$defaultPath" = "false" ] && exit ; \

# Add ssh key to agent.
ssh-add ~/.ssh/id_rsa
