#!/usr/bin/env bash
# remove zzy scripts broken symbolic links on /usr/bin if any
find ~/bin/ -xtype l -name "zzy-*" -exec sudo rm {} \; && \
# report deletion
echo "broken symbolic links deleted" ; \
# create symbolic links for zzy scripts as needed. Discard output
find /opt/zzy/ -name "zzy-*" -exec sudo ln -s {} ~/bin/  \; && \
echo "new scripts symbolic links added" ;\
# make zzy scripts executable
find /opt/zzy/ -name "zzy-*" -exec chmod +x {} \; && \
echo "new zzy- scripts are now ready to use, have fun :D"
